In [1]:
##Sort, search and Counting Functions.

In [3]:
import numpy as np

In [9]:
arr = np.array([8,6,3,5,4,9,12])

In [10]:
arr

array([ 8,  6,  3,  5,  4,  9, 12])

In [11]:
np.sort(arr)

array([ 3,  4,  5,  6,  8,  9, 12])

In [12]:
np.searchsorted(arr,2)

0

In [14]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [15]:
np.count_nonzero(arr1)

6

In [16]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9]),)

In [18]:
np.extract(arr >2,arr1)

array([  0, 324, 645,  65,   6,   6,   0])

In [19]:
# Numpy - Byte Swapping.

In [20]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [24]:
arr.byteswap(True)

array([576460752303423488, 432345564227567616, 216172782113783808,
       360287970189639680, 288230376151711744, 648518346341351424,
       864691128455135232])

In [25]:
arr

array([576460752303423488, 432345564227567616, 216172782113783808,
       360287970189639680, 288230376151711744, 648518346341351424,
       864691128455135232])

In [26]:
arr

array([576460752303423488, 432345564227567616, 216172782113783808,
       360287970189639680, 288230376151711744, 648518346341351424,
       864691128455135232])

In [27]:
#Numpy - Copies and Views.

In [28]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [29]:
a = np.copy(arr1)

In [31]:
b = arr1.view()

In [32]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [33]:
b[0] = 234

In [34]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [35]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [36]:
# Numpy - Matrix Library

In [37]:
import numpy.matlib as nm

In [38]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [39]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [41]:
##Numpy - Linear Algebra

In [45]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [46]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [47]:
arr1

array([[0, 2],
       [0, 0]])

In [48]:
arr2

array([[0, 1],
       [0, 1]])

In [49]:
# dot product of this two array
np.dot(arr1,arr2)

array([[0, 2],
       [0, 0]])

In [50]:
arr1@arr2

array([[0, 2],
       [0, 0]])